apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix-authentication-service.fullname" . }}
  labels:
    {{- include "matrix-authentication-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "matrix-authentication-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matrix-authentication-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "matrix-authentication-service.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: cp-existing-config-to-data-dir
          image: debian:bookworm-slim
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              cp /initial/config.yaml /data/config.yaml
          volumeMounts:
            - name: initial-config
              mountPath: "/initial"
            - name: config
              mountPath: /data
        {{- if not .Values.existingMasConfigSecret }}
        - name: mas-cli-generate-config-secrets
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['config', 'generate', '-o', '/data/config-secrets.yaml']
          volumeMounts:
            - name: config
              mountPath: /data

        - name: add-secret-values-to-config
          image: mikefarah/yq:4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - '-exc'
            - /scripts/templateconfig.sh
          volumeMounts:
            - name: templating-script
              mountPath: /scripts
            - name: config
              mountPath: /data
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: MATRIX_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-authentication-service.matrix.secretName" . }}
                  key: {{ include "matrix-authentication-service.matrix.secretKey" . }}
            - name: MATRIX_HOMESERVER
              value: {{ .Values.mas.matrix.homeserver }}
            - name: MATRIX_ENDPOINT
              value: {{ .Values.mas.matrix.endpoint }}
            {{- if .Values.mas.upstream_oauth2.existingSecret }}
            {{- if .Values.mas.upstream_oauth2.secretKeys.issuer }}
            - name: ISSUER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.upstream_oauth2.existingSecret }}
                  key: {{ .Values.mas.upstream_oauth2.secretKeys.issuer }}
            {{- end }} {{/* end oauth2 issuer */}}
            {{- if .Values.mas.upstream_oauth2.secretKeys.id }}
            - name: PROVIDER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.upstream_oauth2.existingSecret }}
                  key: {{ .Values.mas.upstream_oauth2.secretKeys.id }}
            {{- end }} {{/* end oauth2 provider id */}}
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.upstream_oauth2.existingSecret }}
                  key: {{ .Values.mas.upstream_oauth2.secretKeys.client_id }}
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.upstream_oauth2.existingSecret }}
                  key: {{ .Values.mas.upstream_oauth2.secretKeys.client_secret}}
            {{- if .Values.mas.upstream_oauth2.secretKeys.authorization_endpoint}}
            - name: AUTH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.upstream_oauth2.existingSecret }}
                  key: {{ .Values.mas.upstream_oauth2.secretKeys.authorization_endpoint }}
            {{- end }} {{/* end auth endpoint */}}
            {{- if .Values.mas.upstream_oauth2.secretKeys.token_endpoint }}
            - name: TOKEN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.upstream_oauth2.existingSecret }}
                  key: {{ .Values.mas.upstream_oauth2.secretKeys.token_endpoint }}
            {{- end }} {{/* end token endpoint */}}
            {{- if .Values.mas.upstream_oauth2.secretKeys.userinfo_endpoint }}
            - name: USERINFO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.upstream_oauth2.existingSecret }}
                  key: {{ .Values.mas.upstream_oauth2.secretKeys.userinfo_endpoint }}
            {{- end }} {{/* user info endpoint */}}
            {{- end }} {{/* end check for oauth2 existing secret */}}
            {{- if .Values.mas.masClientSecret.existingSecret }}
            - name: MAS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.masClientSecret.existingSecret }}
                  key: {{ .Values.mas.masClientSecret.secretKeys.client_id }}

            - name: MAS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.masClientSecret.existingSecret }}
                  key: {{ .Values.mas.masClientSecret.secretKeys.client_secret }}
            {{- end }}{{/* end check for existing mas client secrets */}}

            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-authentication-service.postgresql.secretName" . }}
                  key: {{ include "matrix-authentication-service.postgresql.secretKeys.hostname" . }}
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-authentication-service.postgresql.secretName" . }}
                  key: {{ include "matrix-authentication-service.postgresql.secretKeys.database" . }}
            - name: PGPORT
              value: {{ include "matrix-authentication-service.postgresql.port" . | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-authentication-service.postgresql.secretName" . }}
                  key: {{ include "matrix-authentication-service.postgresql.secretKeys.user" . }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-authentication-service.postgresql.secretName" . }}
                  key: {{ include "matrix-authentication-service.postgresql.secretKeys.password" . }}
            {{- if or .Values.postgresql.sslmode .Values.externalDatabase.sslmode }}
            {{- include "matrix-authentication-service.postgresql.sslEnvVars" . | nindent 12 }}
            {{- end }}
        {{- end }} {{/* end if not existingMasConfigSecret */}}
        {{- if .Values.postgresql.enabled }}
        - name: postgresql-isready
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          command:
            - "sh"
            - "-c"
            - "until pg_isready -h $PGHOST -U $PGUSER; do sleep 2; done"
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-authentication-service.postgresql.secretName" . }}
                  key: {{ include "matrix-authentication-service.postgresql.secretKeys.hostname" . }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-authentication-service.postgresql.secretName" . }}
                  key: {{ include "matrix-authentication-service.postgresql.secretKeys.user" . }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-authentication-service.postgresql.secretName" . }}
                  key: {{ include "matrix-authentication-service.postgresql.secretKeys.password" . }}
            {{- if or .Values.postgresql.sslmode .Values.externalDatabase.sslmode }}
            {{- include "matrix-authentication-service.postgresql.sslEnvVars" . | nindent 12 }}
            {{- end }}
        {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['server']
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: MAS_CONFIG
              value: /data/config.yaml
            {{- if or .Values.postgresql.sslmode .Values.externalDatabase.sslmode }}
            {{- include "matrix-authentication-service.postgresql.sslEnvVars" . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /data
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: templating-script
          configMap:
            name: {{ include "matrix-authentication-service.fullname" . }}-templating-script
            defaultMode: 0755

        - name: initial-config
          secret:
            {{ if .Values.existingMasConfigSecret }}
            secretName: {{ .Values.existingMasConfigSecret }}
            {{- else -}}
            secretName: {{ template "matrix-authentication-service.fullname" . }}-initial-config-secret
            {{- end }}

        - name: config
          persistentVolumeClaim:
            {{ if .Values.configVolume.existingClaim }}
            claimName: {{ .Values.configVolume.existingClaim }}
            {{- else -}}
            claimName: {{ include "matrix-authentication-service.fullname" . }}-config
            {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
