{{- if not .Values.existingMasConfigSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix-authentication-service.fullname" . }}-initial-config-secret
stringData:
  config.yaml: |
    http:
      {{- with .Values.mas.http.public_base }}
      public_base: {{ . }}
      {{- end }}
      {{- with .Values.mas.http.issuer }}
      issuer: {{ . }}
      {{- end }}
      listeners:
        {{- range .Values.mas.http.listeners }}
        - name: {{ .name }}
          resources:
            {{- range .resources }}
            - name: {{ .name }}
              {{- if (hasKey . "playground") }}
              playground: {{ .playground }}
              {{- else if (hasKey . "path") }}
              path: {{ .path }}
              {{- end }}
            {{- end }}{{/* end range over listeners[].resources */}}

          binds:
            {{- range .binds }}
            {{- if (hasKey . "address") }}
            - address: {{ .address }}
            {{- else if (hasKey . "host") }}
            - host: {{ .host }}
              port: {{ .port }}
            {{- else if (hasKey . "socket") }}
            - socket: {{ .socket }}
            {{- else if (hasKey . "fd") }}
            - fd: {{ .fd }}
              kind: {{ .kind }}
            {{- end }}{{/* end hasKey else ifs for binds */}}
            {{- end }}{{/* end range over listeners[].binds */}}

          proxy_protocol: {{ .proxy_protocol }}
          {{- with .tls }}
          tls:
          {{ toYaml . | indent 10 }}
          {{- end }}{{/* end with listeners[].tls section */}}
        {{- end }}{{/* end http.listeners */}}

    database:
      {{- with .Values.mas.database }}
      {{- toYaml . | nindent 6 }}
      {{- end }}{{/* end with mas.database */}}

    clients:
      {{- range .Values.mas.clients }}
      - client_auth_method: {{ .client_auth_method }}
        client_id: {{ .client_id }}
        client_secret: {{ .client_secret }}
        {{- if .redirect_uris }}
        redirect_uris:
          {{- range .redirect_uris }}
          - {{ . }}
          {{- end }}{{/* end range redirect_uris */}}
        {{- end }}{{/* end if redirect_uris */}}
      {{- end }}{{/* end range clients */}}

    matrix:
      homeserver: "{{ .Values.mas.matrix.homeserver }}"
      secret: "REPLACE_ME"
      endpoint: "{{ .Values.mas.matrix.endpoint }}"

    passwords:
      enabled: {{ .Values.mas.passwords.enabled }}
      {{- if hasKey .Values.mas.passwords "schemes" }}
      schemes:
        {{- range .Values.mas.passwords.schemes }}
        - version: {{ .version }}
          algorithm: {{ .algorithm }}
        {{- end }}
      {{- end }}{{/* end if passwords.schemes */}}

    email:
      transport: {{ .Values.mas.email.transport }}
      {{- if not (eq .Values.mas.email.transport "blackhole") }}
      from: {{ .Values.mas.email.from | quote }}
      reply_to: {{ .Values.mas.email.reply_to | quote }}
      {{- if (eq .Values.mas.email.transport "smtp") }}
      mode: {{ .Values.mas.email.mode }}
      hostname: {{ .Values.mas.email.hostname }}
      port: {{ .Values.mas.email.port }}
      username: {{ .Values.mas.email.username }}
      password: {{ .Values.mas.email.password }}
      {{- else if (eq .Values.mas.email.transport "sendmail") }}
      command: {{ .Values.mas.email.command }}
      {{- end }}
      {{- end }}{{/* end if not blackhole */}}

    captcha:
      service: {{ .Values.mas.captcha.service }}
      {{- if not (eq .Values.mas.captcha.service "~") }}
      site_key: {{ .Values.mas.captcha.site_key }}
      secret_key: {{ .Values.mas.captcha.secret_key }}
      {{- end }}{{/* end extra service parameters */}}

    policy:
      data:
        admin_users:
          {{- range .Values.mas.policy.data.admin_users }}
          - {{ . }}
          {{- end }}
        admin_clients:
          {{- range .Values.mas.policy.data.admin_clients }}
          - {{ . }}
          {{- end }}

        {{- with .client_registration }}
        client_registration:
        {{ toYaml . | indent 6 }}
        {{- end }}

        {{- with .client_registration }}
        passwords:
        {{ toYaml . | indent 6 }}
        {{- end }}

    upstream_oauth2:
      providers:
        {{- range .Values.mas.upstream_oauth2.providers }}
        - id: {{ .id }}
          issuer: {{ .issuer }}
          {{- with .human_name }}
          human_name: {{ . }}
          {{- end }}
          {{- with .brand_name }}
          brand_name: {{ . }}
          {{- end }}
          client_id: {{ .client_id }}
          client_secret: {{ .client_secret }}
          token_endpoint_auth_method: {{ .token_endpoint_auth_method }}
          {{- if (hasKey . "token_endpoint_auth_signing_alg") }}
          token_endpoint_auth_signing_alg: {{ .token_endpoint_auth_method }}
          {{- end }}
          scope: {{ .scope }}
          discovery_mode: {{ .discovery_mode }}
          pkce_method: {{ .pkce_method }}
          {{- if (hasKey . "authorization_endpoint") }}
          {{- if .authorization_endpoint }}
          authorization_endpoint: {{ .authorization_endpoint }}
          {{- end }}
          {{- end }}
          {{- if (hasKey . "token_endpoint") }}
          {{- if .token_endpoint }}
          token_endpoint: {{ .token_endpoint }}
          {{- end }}
          {{- end }}
          {{- if (hasKey . "jwks_uri") }}
          {{- if .jwks_uri }}
          jwks_uri: {{ .jwks_uri }}
          {{- end }}
          {{- end }}
          claims_imports:
            subject:
              template: "{{ .claims_imports.subject.template }}"
            localpart:
              action: {{ .claims_imports.localpart.action }}
              template: "{{ .claims_imports.localpart.template }}"
            displayname:
              action: {{ .claims_imports.displayname.action }}
              template: "{{ .claims_imports.displayname.template }}"
            email:
              action: {{ .claims_imports.email.action }}
              template: "{{ .claims_imports.email.template }}"
              set_email_verification: {{ .claims_imports.email.set_email_verification }}
        {{- end }}{{/* end range providers */}}

{{- end }}
